version: '3.3'

services:
  irc-mqtt:
    image: stigok/irc-mqtt-bot
    build: .
    restart: always
    environment:
      IRC_SERVER: "chat.freenode.net"
      BOTNAME: "sshowbot"
      HOMECHAN: "#hackeriet"
      MQTT_CNNSTRING: "mqtt://alarm:alarm@mqtt-server"
      ROOT_TOPIC: "irc/sshowbot"
      LOG_LEVEL: "silly"
    stop_signal: SIGINT
  mqtt-server:
    image: eclipse-mosquitto:1.4.10
    restart: always
    command: mosquitto -v
    expose:
      - "1883"
