version: '2'

services:
  irc-server:
    image: sshow/irc-mqtt:latest
    build: .
    restart: 'always'
    environment:
      IRC_SERVER: "chat.freenode.net"
      BOTNAME: "sshowbot"
      HOMECHAN: "#oslohackerspace"
      MQTT_CNNSTRING: "mqtts://user:password@localhost:1337"
      ROOT_TOPIC: "sshow/sshowbot"
    stop_signal: SIGINT
